### ISSUE TITLE
problem with tagging software version

### ISSUE THREAD

**Issue by gaede** [iLCSoft/iLCInstall#18]
When I try to tag a new LCIO version, I get the following error:
```
11:03:35-gaede/data/ilcsoft/HEAD/lcio/HEAD/build (master)$ python ~/ilcinstall/HEAD/scripts/ilcsofttagger.py --packages ilcsoft/LCIO/v02-08 --properRelease
INFO  - Tagger  : Checking package: ilcsoft/LCIO/v02-08
Traceback (most recent call last):
  File "/Users/gaede/ilcinstall/HEAD/scripts/ilcsofttagger.py", line 222, in <module>
    RUNNER.run()
  File "/Users/gaede/ilcinstall/HEAD/scripts/ilcsofttagger.py", line 204, in run
    self._printReleaseNotes()
  File "/Users/gaede/ilcinstall/HEAD/scripts/ilcsofttagger.py", line 160, in _printReleaseNotes
    if thisPackage.isUpToDate():
  File "/Users/gaede/ilcinstall/HEAD/scripts/tagging/gitinterface.py", line 506, in isUpToDate
    if self.latestTagInfo['sha'] != self._lastCommitOnBranch['sha']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Is this a bug or am I missing something ?

**Comment by andresailer** [comment]
It is a bug, solved by #19

**Comment by petricm** [comment]
There is still something strange. If you look at the release of (lcgeo0[https://github.com/iLCSoft/lcgeo/releases/tag/v00-11] you see 2017-03-31 luisaleperez (PR#73) and the comment just "and" which is not what is in release notes tag

**Comment by andresailer** [comment]
It is your comment https://github.com/ilcsoft/lcgeo/pull/73#issuecomment-290659540
